// Available tasks from terminal-bench core dataset
export const AVAILABLE_TASKS = [
  'adaptive-rejection-sampler',
  'aimo-airline-departures',
  'attention-mil',
  'blind-maze-explorer-5x5',
  'blind-maze-explorer-algorithm',
  'broken-networking',
  'broken-python',
  'build-initramfs-qemu',
  'build-linux-kernel-qemu',
  'build-tcc-qemu',
  'cartpole-rl-training',
  'causal-inference-r',
  'chem-property-targeting',
  'chem-rf',
  'chess-best-move',
  'circuit-fibsqrt',
  'classifier-debug',
  'cobol-modernization',
  'conda-env-conflict-resolution',
  'configure-git-webserver',
  'count-call-stack',
  'count-dataset-tokens',
  'cpp-compatibility',
  'crack-7z-hash',
  'create-bucket',
  'cron-broken-network',
  'cross-entropy-method',
  'csv-to-parquet',
  'decommissioning-service-with-sensitive-data',
  'download-youtube',
  'enemy-grid-escape',
  'eval-mteb',
  'extract-elf',
  'extract-moves-from-video',
  'extract-safely',
  'feal-differential-cryptanalysis',
  'feal-linear-cryptanalysis',
  'fibonacci-server',
  'fix-git',
  'fix-pandas-version',
  'fix-permissions',
  'form-filling',
  'gcc-compiler-optimization',
  'get-bitcoin-nodes',
  'git-multibranch',
  'git-workflow-hack',
  'gpt2-codegolf',
  'grid-pattern-transform',
  'hdfs-deployment',
  'hello-world',
  'heterogeneous-dates',
  'hf-model-inference',
  'home-server-https',
  'incompatible-python-fasttext',
  'install-windows-3.11',
  'install-windows-xp',
  'intrusion-detection',
  'jq-data-processing',
  'jupyter-notebook-server',
  'kv-store-grpc',
  'lean4-proof',
  'logistic-regression-divergence',
  'make-doom-for-mips',
  'make-mips-interpreter',
  'mixed-integer-programming-1',
  'mlflow-register',
  'modernize-fortran-build',
  'neuron-to-jaxley-conversion',
  'new-encrypt-command',
  'nginx-request-logging',
  'npm-conflict-resolution',
  'oom',
  'openssl-selfsigned-cert',
  'organization-json-generator',
  'pandas-etl',
  'pandas-sql-query',
  'parallel-particle-simulator',
  'parallelize-graph',
  'password-recovery',
  'path-tracing',
  'path-tracing-reverse',
  'pcap-to-netflow',
  'play-zork',
  'polyglot-c-py',
  'polyglot-rust-c',
  'processing-pipeline',
  'prove-plus-comm',
  'pytorch-model-cli',
  'pytorch-model-recovery',
  'qemu-alpine-ssh',
  'qemu-startup',
  'raman-fitting',
  'rare-mineral-allocation',
  'recover-obfuscated-files',
  'reshard-c4-data',
  'reverse-engineering',
  'run-pdp11-code',
  'sanitize-git-repo',
  'security-vulhub-minio',
  'setup-custom-dev-env',
  'simple-sheets-put',
  'simple-web-scraper',
  'slurm-simple-node-monitoring',
  'solana-data',
  'solve-maze-challenge',
  'sqlite-db-truncate',
  'sqlite-with-gcov',
  'stable-parallel-kmeans',
  'super-benchmark-upet',
  'swe-bench-astropy-1',
  'swe-bench-astropy-2',
  'swe-bench-fsspec',
  'swe-bench-langcodes',
  'tmux-advanced-workflow',
  'train-fasttext',
  'tree-directory-parser',
  'vim-terminal-task',
  'weighted-max-sat-solver',
  'word2vec-from-scratch',
  'write-compressor'
] as const;

// Common task categories for quick selection
export const TASK_CATEGORIES = {
  'Quick Test': ['hello-world', 'fibonacci-server'],
  'Programming': ['chess-best-move', 'classifier-debug', 'gpt2-codegolf'],
  'System Admin': ['fix-permissions', 'configure-git-webserver', 'nginx-request-logging'],
  'Security': ['crack-7z-hash', 'password-recovery', 'security-vulhub-minio'],
  'Data Processing': ['csv-to-parquet', 'pandas-etl', 'jq-data-processing'],
  'ML/AI': ['cartpole-rl-training', 'pytorch-model-cli', 'eval-mteb'],
  'Build Systems': ['build-tcc-qemu', 'gcc-compiler-optimization', 'modernize-fortran-build'],
  'Comprehensive Test': ['sqlite-with-gcov', 'fibonacci-server', 'build-tcc-qemu', 'password-recovery', 'crack-7z-hash']
} as const;